apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aperio.secretName" . }}
  labels:
    {{- include "aperio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.auth.discoveryUrl (not .Values.auth.discoveryUrlRef.secretName) }}
  oidc-discovery-url: {{ .Values.auth.discoveryUrl | b64enc | quote }}
  {{- end }}
  {{- if and .Values.sync.token (not .Values.sync.tokenRef.secretName) }}
  sync-token: {{ .Values.sync.token | b64enc | quote }}
  {{- end }}
