apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aperio.secretName" . }}
  labels:
    {{- include "aperio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.enabled }}
  oidc-issuer-url: {{ .Values.auth.issuerUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.sync.token }}
  sync-token: {{ .Values.sync.token | b64enc | quote }}
  {{- end }}
